import { useState } from 'react'
import { useSearchParams, useNavigate } from 'react-router-dom'
import Navbar from '../components/Navbar'
import { getIdeaById, getIdeas, getCurrentUser } from '../utils/storage'

const tabs = [
  { key: 'plan', label: '7-Day Plan' },
  { key: 'interview', label: 'Interview Questions' },
  { key: 'email', label: 'Cold Email' },
  { key: 'mvp', label: 'MVP Test Plan' },
]

const ValidationPlanPage = () => {
  const [searchParams] = useSearchParams()
  const navigate = useNavigate()
  const id = searchParams.get('id')

  let idea = getIdeaById(id)
  if (!idea) {
    const all = getIdeas()
    if (all.length > 0) {
      idea = all[0]
    }
  }

  if (!idea) {
    return (
      <div className="min-h-screen bg-[#F8F9FA] flex flex-col justify-center items-center p-6 text-center">
        <h2 className="text-xl font-bold text-gray-900 mb-2">No active validation plan found</h2>
        <p className="text-gray-500 mb-4 text-sm">Please submit a startup idea first to generate a validation plan.</p>
        <button
          onClick={() => navigate('/submit')}
          className="bg-[#534AB7] text-white px-5 py-2.5 rounded-lg font-semibold hover:bg-[#4840a0] transition-colors"
        >
          Submit your first idea
        </button>
      </div>
    )
  }

  const user = getCurrentUser()
  const userName = user ? `${user.firstName} ${user.lastName || ''}`.trim() : 'Arun Kumar'

  const {
    startupName,
    planDays,
    interviewQuestions,
    emailText,
    mvpItems
  } = idea

  const [activeTab, setActiveTab] = useState('plan')
  const [copied, setCopied] = useState(false)

  const customizedEmail = emailText.replace('[Your Name]', userName)
  const emailParagraphs = customizedEmail.split('\n\n')
  const subjectText = `Quick question about your ${
    idea.industry === 'EdTech'
      ? 'learning'
      : idea.industry === 'FinTech'
      ? 'finance'
      : idea.industry === 'HealthTech'
      ? 'healthcare'
      : idea.industry === 'AgriTech'
      ? 'farming'
      : idea.industry === 'Logistics'
      ? 'logistics'
      : 'industry'
  } experience`

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(customizedEmail)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // Fallback silently
    }
  }

  return (
    <div className="min-h-screen bg-[#F8F9FA]">
      <Navbar>
        <button className="inline-flex items-center gap-1.5 rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-semibold text-gray-700 shadow-sm transition-all hover:bg-gray-50 hover:shadow-md active:scale-[0.97]">
          <svg
            className="w-4 h-4"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth="2"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
            />
          </svg>
          Export PDF
        </button>
      </Navbar>

      <main className="min-h-[calc(100vh-4rem)] py-8 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          {/* Page Heading */}
          <div>
            <h1 className="text-2xl font-bold text-gray-900">
              Validation Plan — {startupName}
            </h1>
            <p className="text-sm text-gray-500 mt-1">
              Generated by AI · 7-day action plan
            </p>
          </div>

          {/* Tab Bar */}
          <div className="mt-6 mb-8 overflow-x-auto">
            <div className="inline-flex rounded-lg bg-gray-100 p-1 border border-gray-200">
              {tabs.map((tab) => (
                <button
                  key={tab.key}
                  onClick={() => setActiveTab(tab.key)}
                  className={
                    activeTab === tab.key
                      ? 'bg-white text-gray-900 shadow-sm border border-gray-200 rounded-md px-4 py-2 text-sm font-medium'
                      : 'text-gray-500 hover:text-gray-700 rounded-md px-4 py-2 text-sm font-medium transition-colors'
                  }
                  aria-selected={activeTab === tab.key}
                  role="tab"
                >
                  {tab.label}
                </button>
              ))}
            </div>
          </div>

          {/* Tab 1 — 7-Day Plan */}
          {activeTab === 'plan' && (
            <div className="space-y-4">
              {planDays.map((item) => (
                <div
                  key={item.day}
                  className="bg-white rounded-xl border border-gray-200 p-5 shadow-sm flex gap-4"
                >
                  <div
                    className={`w-9 h-9 rounded-full flex items-center justify-center text-sm font-bold text-white flex-shrink-0 ${
                      item.day <= 5 ? 'bg-[#534AB7]' : 'bg-emerald-500'
                    }`}
                  >
                    {item.day}
                  </div>
                  <div>
                    <h3 className="text-sm font-semibold text-gray-900">
                      {item.title}
                    </h3>
                    <p className="text-sm text-gray-600 mt-1 leading-relaxed">
                      {item.description}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Tab 2 — Interview Questions */}
          {activeTab === 'interview' && (
            <div className="bg-white rounded-xl border border-gray-200 p-6 shadow-sm">
              <h2 className="text-base font-semibold text-gray-900 mb-4">
                Customer interview questions
              </h2>
              <div>
                {interviewQuestions.map((question, index) => (
                  <div
                    key={index}
                    className="bg-gray-50 rounded-lg px-4 py-3 mb-3 text-sm text-gray-700 leading-relaxed border border-gray-100"
                  >
                    {question}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Tab 3 — Cold Email */}
          {activeTab === 'email' && (
            <div className="bg-white rounded-xl border border-gray-200 p-6 shadow-sm">
              <p className="text-sm font-semibold text-gray-900 mb-4">
                <span className="text-gray-500">Subject: </span>
                {subjectText}
              </p>
              <div className="text-sm text-gray-600 leading-relaxed space-y-3">
                {emailParagraphs.map((para, index) => (
                  <p key={index} className="whitespace-pre-line">
                    {para}
                  </p>
                ))}
              </div>
              <div className="mt-4">
                <button
                  onClick={handleCopy}
                  className="rounded-lg border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 transition inline-flex items-center gap-2"
                >
                  <svg
                    className="w-4 h-4"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth="2"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                    />
                  </svg>
                  {copied ? 'Copied!' : 'Copy to clipboard'}
                </button>
              </div>
            </div>
          )}

          {/* Tab 4 — MVP Test Plan */}
          {activeTab === 'mvp' && (
            <div className="bg-white rounded-xl border border-gray-200 p-6 shadow-sm">
              <h2 className="text-base font-semibold text-gray-900 mb-5">
                MVP testing roadmap
              </h2>
              <div className="space-y-4">
                {mvpItems.map((item, index) => (
                  <div key={index} className="flex gap-4 items-start">
                    <span
                      className={`inline-flex px-3 py-1 rounded-full text-xs font-semibold flex-shrink-0 mt-0.5 ${item.badgeClasses}`}
                    >
                      {item.badge}
                    </span>
                    <div>
                      <h3 className="text-sm font-semibold text-gray-900">
                        {item.title}
                      </h3>
                      <p className="text-sm text-gray-600 mt-1">
                        {item.description}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </main>
    </div>
  )
}

export default ValidationPlanPage
